; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
lib_deps =

    ; RTC DS3231 - Sensor de relógio em tempo real
    adafruit/RTClib
    adafruit/Adafruit BusIO

    ; DHT11 - Sensor de temperatura e umidade do ar
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

    ; DS18B20 - Sensor de temperatura da água
    paulstoffregen/OneWire
    milesburton/DallasTemperature

