; PlatformIO Project Configuration File
;
; Documentação:
; https://docs.platformio.org/page/projectconf.html

; COMMAND + / PARA COMENTAR TUDO

[platformio]
default_envs = esp32-micro


; Ambiente antigo da placa USB-C/NodeMCU-32S
; Mantido comentado porque a placa apresentou possível defeito físico
; [env:nodemcu-32s]
; platform = espressif32
; board = nodemcu-32s
; framework = arduino
; monitor_speed = 115200
; upload_speed = 115200


; Ambiente atual da placa ESP32 micro USB
[env:esp32-micro]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =

    ; RTC DS3231 - Biblioteca principal para usar o módulo de relógio em tempo real
    adafruit/RTClib

    ; Dependência usada pela RTClib e por alguns módulos da Adafruit para comunicação I2C/SPI
    adafruit/Adafruit BusIO

    ; DHT11 - Biblioteca usada para ler temperatura e umidade do ar
    adafruit/DHT sensor library

    ; Dependência da biblioteca DHT, usada para padronizar sensores da Adafruit
    adafruit/Adafruit Unified Sensor

    ; DS18B20 - Biblioteca de comunicação OneWire, necessária para o sensor de temperatura da água
    paulstoffregen/OneWire

    ; DS18B20 - Biblioteca específica para ler sensores Dallas/Maxim, como o DS18B20
    milesburton/DallasTemperature